
server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.81.130
jwt:
  token:
    pubKeyPath: E:\\gmall-rsa\\rsa.pub
    cookieName: gmall_token
    userKey: user_key
    expire: 1433223